### ISSUE TITLE
모바일에서 hover 효과 제거하기

### ISSUE THREAD

**Issue by rigood** [rigood/weekly-planner#1]
스마트폰은 마우스가 없기 때문에 원칙적으로 hover가 불가능함
hover가 가능한 장치에서만 hover 효과를 적용하는 미디어 쿼리는 다음과 같다고 알려져 있음

```css
@media (hover:hover){
  &:hover{
    color: red;
  }
}
```

하지만 실제 스마트폰에서 테스트를 해보면 스마트폰에서도 hover 효과가 적용되고 있음
(ex: 요소를 살짝 클릭하면 해당 요소를 hover한 것으로 인식해 hover 스타일을 적용해버림) 

갤럭시s8, 갤럭시s22(터치펜슬 있음) 기준으로 hover, pointer 여부는 아래와 같음
(다른 스마트폰은 아직 확인 안해봄)
```css
(hover: hover)
(pointer: coarse)
(any-hover: hover)
(any-pointer: coarse, fine)
```

실제로 hover가 이루어지지는 않지만
미디어쿼리상으로 스마트폰은 hover: hover에 해당하는 장치임

따라서 마우스가 있는 데스크탑에서만 hover 효과를 적용하려면
아래와 같이 pointer 조건까지 걸어줘야함

```css
@media (hover:hover) and (pointer:fine){
  &:hover{
    color: red;
  }
}
```
